[build]
  base = "/"
  command = "npm run build:all"
  publish = "dist"

[functions]
  directory = "server/src"
  node_bundler = "esbuild"

# Client site redirects
[[redirects]]
  from = "/"
  to = "/client/*"
  status = 200

# Admin panel redirects
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Fallback redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[dev]
  framework = "vite"
  targetPort = 5173

# Environment variables will be configured in Netlify dashboard
# VITE_SUPABASE_URL
# VITE_SUPABASE_ANON_KEY
# Other environment variables 