[build]
  base = "admin"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Ensure security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*.mjs"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html"

# Development settings
[dev]
  framework = "vite"
  targetPort = 5174
  port = 8888
